# Example PHP Schema file
# Use the following command to regenerate entities:
# bin/schema generate-types src/ app/config/schema.yml

rdfa:
  - https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-gozer/data/schema.rdfa
annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator
namespaces:
  entity: AppBundle\Entity
types:
  Person:
    parent: false
    doctrine:
      inheritanceMapping: "@MappedSuperclass"
    abstract: true
    properties:
      name: ~
      description: ~
      url: ~
      birthDate: ~
      gender: ~
  Product:
    parent: false
    doctrine:
      inheritanceMapping: "@MappedSuperclass"
    abstract: true
    properties:
      name: ~
      description: ~
      image: ~
