security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CUSTOMER:    ROLE_USER
        ROLE_FARMER:      ROLE_CUSTOMER
        ROLE_ADMIN:       ROLE_FARMER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            provider: fos_userbundle
            stateless: true
            anonymous: true
            form_login:
                check_path:     /login_check
                require_previous_session: false
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/
            stateless: true
            anonymous: true
            provider: fos_userbundle
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer
                throw_exceptions:        false
                create_entry_point:      true
            logout:
                path: /logout
                success_handler: acme.user.authentication.handler.logout_success_handler

        default:
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/,      roles: [IS_AUTHENTICATED_FULLY]}
        - { path: ^/,      roles: [ROLE_ADMIN],      methods: [POST, PUT, DELETE]}
