# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    faker.provider.foo:
        class: AppBundle\DataFixtures\Faker\Provider\FooProvider
        tags: [ { name: hautelook_alice.faker.provider } ]
# Examples of API resource mapping, learn more at
# https://github.com/dunglas/DunglasApiBundle

    resource.customer:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\User\\Customer" ]
        tags:      [ { name: "api.resource" } ]

    resource.admin:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\User\\Admin" ]
        tags:      [ { name: "api.resource" } ]

    resource.farmer:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\User\\Farmer" ]
        tags:      [ { name: "api.resource" } ]

    resource.basket:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Basket" ]
        tags:      [ { name: "api.resource" } ]

    resource.fruit:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Product\\Fruit" ]
        tags:      [ { name: "api.resource" } ]

    resource.vegetable:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Product\\Vegetable" ]
        tags:      [ { name: "api.resource" } ]

    resource.organization.filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { "name": "exact", "url": "partial" } ]

# A typical service
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
