services:
    form_serializer:
        class: Acme\UserBundle\Serializer\FormErrorsSerializer
    acme.user.mailer:
        class: Acme\UserBundle\Mailer\Mailer
        arguments:
            - @mailer
            - @router
            - @templating.engine.twig
            -
                confirmation.template: %fos_user.registration.confirmation.template%
                resetting.template: %fos_user.resetting.email.template%
                from_email:
                    confirmation: %fos_user.registration.confirmation.from_email%
                    resetting: %fos_user.resetting.email.from_email%
        calls:
            - [setRequest, [@request_stack]]
